# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\pyproject\X光片分析\20191102m-7\SpineFusion.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SpineFusion(object):
    def setupUi(self, SpineFusion):
        SpineFusion.setObjectName("SpineFusion")
        SpineFusion.resize(680, 491)
        self.layoutWidget = QtWidgets.QWidget(SpineFusion)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 661, 461))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.BN_Cancel = QtWidgets.QPushButton(self.layoutWidget)
        self.BN_Cancel.setObjectName("BN_Cancel")
        self.gridLayout.addWidget(self.BN_Cancel, 3, 0, 1, 1)
        self.BN_Confirm = QtWidgets.QPushButton(self.layoutWidget)
        self.BN_Confirm.setObjectName("BN_Confirm")
        self.gridLayout.addWidget(self.BN_Confirm, 3, 1, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.layoutWidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.layoutWidget_2 = QtWidgets.QWidget(self.groupBox_3)
        self.layoutWidget_2.setGeometry(QtCore.QRect(20, 40, 591, 23))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.CB_Fusion3_1 = QtWidgets.QComboBox(self.layoutWidget_2)
        self.CB_Fusion3_1.setObjectName("CB_Fusion3_1")
        self.CB_Fusion3_1.addItem("")
        self.CB_Fusion3_1.addItem("")
        self.CB_Fusion3_1.addItem("")
        self.CB_Fusion3_1.addItem("")
        self.CB_Fusion3_1.addItem("")
        self.CB_Fusion3_1.addItem("")
        self.CB_Fusion3_1.addItem("")
        self.CB_Fusion3_1.addItem("")
        self.CB_Fusion3_1.addItem("")
        self.CB_Fusion3_1.addItem("")
        self.CB_Fusion3_1.addItem("")
        self.CB_Fusion3_1.addItem("")
        self.CB_Fusion3_1.addItem("")
        self.CB_Fusion3_1.addItem("")
        self.CB_Fusion3_1.addItem("")
        self.CB_Fusion3_1.addItem("")
        self.CB_Fusion3_1.addItem("")
        self.CB_Fusion3_1.addItem("")
        self.CB_Fusion3_1.addItem("")
        self.horizontalLayout_3.addWidget(self.CB_Fusion3_1)
        self.CB_Fusion3_2 = QtWidgets.QComboBox(self.layoutWidget_2)
        self.CB_Fusion3_2.setObjectName("CB_Fusion3_2")
        self.CB_Fusion3_2.addItem("")
        self.CB_Fusion3_2.addItem("")
        self.CB_Fusion3_2.addItem("")
        self.CB_Fusion3_2.addItem("")
        self.CB_Fusion3_2.addItem("")
        self.CB_Fusion3_2.addItem("")
        self.CB_Fusion3_2.addItem("")
        self.CB_Fusion3_2.addItem("")
        self.CB_Fusion3_2.addItem("")
        self.CB_Fusion3_2.addItem("")
        self.CB_Fusion3_2.addItem("")
        self.CB_Fusion3_2.addItem("")
        self.CB_Fusion3_2.addItem("")
        self.CB_Fusion3_2.addItem("")
        self.CB_Fusion3_2.addItem("")
        self.CB_Fusion3_2.addItem("")
        self.CB_Fusion3_2.addItem("")
        self.CB_Fusion3_2.addItem("")
        self.CB_Fusion3_2.addItem("")
        self.horizontalLayout_3.addWidget(self.CB_Fusion3_2)
        self.CB_Fusion3_3 = QtWidgets.QComboBox(self.layoutWidget_2)
        self.CB_Fusion3_3.setObjectName("CB_Fusion3_3")
        self.CB_Fusion3_3.addItem("")
        self.CB_Fusion3_3.addItem("")
        self.CB_Fusion3_3.addItem("")
        self.CB_Fusion3_3.addItem("")
        self.CB_Fusion3_3.addItem("")
        self.CB_Fusion3_3.addItem("")
        self.CB_Fusion3_3.addItem("")
        self.CB_Fusion3_3.addItem("")
        self.CB_Fusion3_3.addItem("")
        self.CB_Fusion3_3.addItem("")
        self.CB_Fusion3_3.addItem("")
        self.CB_Fusion3_3.addItem("")
        self.CB_Fusion3_3.addItem("")
        self.CB_Fusion3_3.addItem("")
        self.CB_Fusion3_3.addItem("")
        self.CB_Fusion3_3.addItem("")
        self.CB_Fusion3_3.addItem("")
        self.CB_Fusion3_3.addItem("")
        self.CB_Fusion3_3.addItem("")
        self.horizontalLayout_3.addWidget(self.CB_Fusion3_3)
        self.gridLayout.addWidget(self.groupBox_3, 2, 0, 1, 2)
        self.groupBox_2 = QtWidgets.QGroupBox(self.layoutWidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 40, 591, 23))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.CB_Fusion2_1 = QtWidgets.QComboBox(self.layoutWidget1)
        self.CB_Fusion2_1.setObjectName("CB_Fusion2_1")
        self.CB_Fusion2_1.addItem("")
        self.CB_Fusion2_1.addItem("")
        self.CB_Fusion2_1.addItem("")
        self.CB_Fusion2_1.addItem("")
        self.CB_Fusion2_1.addItem("")
        self.CB_Fusion2_1.addItem("")
        self.CB_Fusion2_1.addItem("")
        self.CB_Fusion2_1.addItem("")
        self.CB_Fusion2_1.addItem("")
        self.CB_Fusion2_1.addItem("")
        self.CB_Fusion2_1.addItem("")
        self.CB_Fusion2_1.addItem("")
        self.CB_Fusion2_1.addItem("")
        self.CB_Fusion2_1.addItem("")
        self.CB_Fusion2_1.addItem("")
        self.CB_Fusion2_1.addItem("")
        self.CB_Fusion2_1.addItem("")
        self.CB_Fusion2_1.addItem("")
        self.CB_Fusion2_1.addItem("")
        self.horizontalLayout_2.addWidget(self.CB_Fusion2_1)
        self.CB_Fusion2_2 = QtWidgets.QComboBox(self.layoutWidget1)
        self.CB_Fusion2_2.setObjectName("CB_Fusion2_2")
        self.CB_Fusion2_2.addItem("")
        self.CB_Fusion2_2.addItem("")
        self.CB_Fusion2_2.addItem("")
        self.CB_Fusion2_2.addItem("")
        self.CB_Fusion2_2.addItem("")
        self.CB_Fusion2_2.addItem("")
        self.CB_Fusion2_2.addItem("")
        self.CB_Fusion2_2.addItem("")
        self.CB_Fusion2_2.addItem("")
        self.CB_Fusion2_2.addItem("")
        self.CB_Fusion2_2.addItem("")
        self.CB_Fusion2_2.addItem("")
        self.CB_Fusion2_2.addItem("")
        self.CB_Fusion2_2.addItem("")
        self.CB_Fusion2_2.addItem("")
        self.CB_Fusion2_2.addItem("")
        self.CB_Fusion2_2.addItem("")
        self.CB_Fusion2_2.addItem("")
        self.CB_Fusion2_2.addItem("")
        self.horizontalLayout_2.addWidget(self.CB_Fusion2_2)
        self.CB_Fusion2_3 = QtWidgets.QComboBox(self.layoutWidget1)
        self.CB_Fusion2_3.setObjectName("CB_Fusion2_3")
        self.CB_Fusion2_3.addItem("")
        self.CB_Fusion2_3.addItem("")
        self.CB_Fusion2_3.addItem("")
        self.CB_Fusion2_3.addItem("")
        self.CB_Fusion2_3.addItem("")
        self.CB_Fusion2_3.addItem("")
        self.CB_Fusion2_3.addItem("")
        self.CB_Fusion2_3.addItem("")
        self.CB_Fusion2_3.addItem("")
        self.CB_Fusion2_3.addItem("")
        self.CB_Fusion2_3.addItem("")
        self.CB_Fusion2_3.addItem("")
        self.CB_Fusion2_3.addItem("")
        self.CB_Fusion2_3.addItem("")
        self.CB_Fusion2_3.addItem("")
        self.CB_Fusion2_3.addItem("")
        self.CB_Fusion2_3.addItem("")
        self.CB_Fusion2_3.addItem("")
        self.CB_Fusion2_3.addItem("")
        self.horizontalLayout_2.addWidget(self.CB_Fusion2_3)
        self.gridLayout.addWidget(self.groupBox_2, 1, 0, 1, 2)
        self.groupBox = QtWidgets.QGroupBox(self.layoutWidget)
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget2 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget2.setGeometry(QtCore.QRect(20, 40, 591, 23))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.CB_Fusion1_1 = QtWidgets.QComboBox(self.layoutWidget2)
        self.CB_Fusion1_1.setObjectName("CB_Fusion1_1")
        self.CB_Fusion1_1.addItem("")
        self.CB_Fusion1_1.addItem("")
        self.CB_Fusion1_1.addItem("")
        self.CB_Fusion1_1.addItem("")
        self.CB_Fusion1_1.addItem("")
        self.CB_Fusion1_1.addItem("")
        self.CB_Fusion1_1.addItem("")
        self.CB_Fusion1_1.addItem("")
        self.CB_Fusion1_1.addItem("")
        self.CB_Fusion1_1.addItem("")
        self.CB_Fusion1_1.addItem("")
        self.CB_Fusion1_1.addItem("")
        self.CB_Fusion1_1.addItem("")
        self.CB_Fusion1_1.addItem("")
        self.CB_Fusion1_1.addItem("")
        self.CB_Fusion1_1.addItem("")
        self.CB_Fusion1_1.addItem("")
        self.CB_Fusion1_1.addItem("")
        self.CB_Fusion1_1.addItem("")
        self.horizontalLayout.addWidget(self.CB_Fusion1_1)
        self.CB_Fusion1_2 = QtWidgets.QComboBox(self.layoutWidget2)
        self.CB_Fusion1_2.setObjectName("CB_Fusion1_2")
        self.CB_Fusion1_2.addItem("")
        self.CB_Fusion1_2.addItem("")
        self.CB_Fusion1_2.addItem("")
        self.CB_Fusion1_2.addItem("")
        self.CB_Fusion1_2.addItem("")
        self.CB_Fusion1_2.addItem("")
        self.CB_Fusion1_2.addItem("")
        self.CB_Fusion1_2.addItem("")
        self.CB_Fusion1_2.addItem("")
        self.CB_Fusion1_2.addItem("")
        self.CB_Fusion1_2.addItem("")
        self.CB_Fusion1_2.addItem("")
        self.CB_Fusion1_2.addItem("")
        self.CB_Fusion1_2.addItem("")
        self.CB_Fusion1_2.addItem("")
        self.CB_Fusion1_2.addItem("")
        self.CB_Fusion1_2.addItem("")
        self.CB_Fusion1_2.addItem("")
        self.CB_Fusion1_2.addItem("")
        self.horizontalLayout.addWidget(self.CB_Fusion1_2)
        self.CB_Fusion1_3 = QtWidgets.QComboBox(self.layoutWidget2)
        self.CB_Fusion1_3.setObjectName("CB_Fusion1_3")
        self.CB_Fusion1_3.addItem("")
        self.CB_Fusion1_3.addItem("")
        self.CB_Fusion1_3.addItem("")
        self.CB_Fusion1_3.addItem("")
        self.CB_Fusion1_3.addItem("")
        self.CB_Fusion1_3.addItem("")
        self.CB_Fusion1_3.addItem("")
        self.CB_Fusion1_3.addItem("")
        self.CB_Fusion1_3.addItem("")
        self.CB_Fusion1_3.addItem("")
        self.CB_Fusion1_3.addItem("")
        self.CB_Fusion1_3.addItem("")
        self.CB_Fusion1_3.addItem("")
        self.CB_Fusion1_3.addItem("")
        self.CB_Fusion1_3.addItem("")
        self.CB_Fusion1_3.addItem("")
        self.CB_Fusion1_3.addItem("")
        self.CB_Fusion1_3.addItem("")
        self.CB_Fusion1_3.addItem("")
        self.horizontalLayout.addWidget(self.CB_Fusion1_3)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 2)

        self.retranslateUi(SpineFusion)
        QtCore.QMetaObject.connectSlotsByName(SpineFusion)

    def retranslateUi(self, SpineFusion):
        _translate = QtCore.QCoreApplication.translate
        SpineFusion.setWindowTitle(_translate("SpineFusion", "锥体融合录入"))
        self.BN_Cancel.setText(_translate("SpineFusion", "取消"))
        self.BN_Confirm.setText(_translate("SpineFusion", "确定"))
        self.groupBox_3.setTitle(_translate("SpineFusion", "第三组锥体融合"))
        self.CB_Fusion3_1.setItemText(0, _translate("SpineFusion", "无"))
        self.CB_Fusion3_1.setItemText(1, _translate("SpineFusion", "颈7"))
        self.CB_Fusion3_1.setItemText(2, _translate("SpineFusion", "胸1"))
        self.CB_Fusion3_1.setItemText(3, _translate("SpineFusion", "胸2"))
        self.CB_Fusion3_1.setItemText(4, _translate("SpineFusion", "胸3"))
        self.CB_Fusion3_1.setItemText(5, _translate("SpineFusion", "胸4"))
        self.CB_Fusion3_1.setItemText(6, _translate("SpineFusion", "胸5"))
        self.CB_Fusion3_1.setItemText(7, _translate("SpineFusion", "胸6"))
        self.CB_Fusion3_1.setItemText(8, _translate("SpineFusion", "胸7"))
        self.CB_Fusion3_1.setItemText(9, _translate("SpineFusion", "胸8"))
        self.CB_Fusion3_1.setItemText(10, _translate("SpineFusion", "胸9"))
        self.CB_Fusion3_1.setItemText(11, _translate("SpineFusion", "胸10"))
        self.CB_Fusion3_1.setItemText(12, _translate("SpineFusion", "胸11"))
        self.CB_Fusion3_1.setItemText(13, _translate("SpineFusion", "胸12"))
        self.CB_Fusion3_1.setItemText(14, _translate("SpineFusion", "腰1"))
        self.CB_Fusion3_1.setItemText(15, _translate("SpineFusion", "腰2"))
        self.CB_Fusion3_1.setItemText(16, _translate("SpineFusion", "腰3"))
        self.CB_Fusion3_1.setItemText(17, _translate("SpineFusion", "腰4"))
        self.CB_Fusion3_1.setItemText(18, _translate("SpineFusion", "腰5"))
        self.CB_Fusion3_2.setItemText(0, _translate("SpineFusion", "无"))
        self.CB_Fusion3_2.setItemText(1, _translate("SpineFusion", "颈7"))
        self.CB_Fusion3_2.setItemText(2, _translate("SpineFusion", "胸1"))
        self.CB_Fusion3_2.setItemText(3, _translate("SpineFusion", "胸2"))
        self.CB_Fusion3_2.setItemText(4, _translate("SpineFusion", "胸3"))
        self.CB_Fusion3_2.setItemText(5, _translate("SpineFusion", "胸4"))
        self.CB_Fusion3_2.setItemText(6, _translate("SpineFusion", "胸5"))
        self.CB_Fusion3_2.setItemText(7, _translate("SpineFusion", "胸6"))
        self.CB_Fusion3_2.setItemText(8, _translate("SpineFusion", "胸7"))
        self.CB_Fusion3_2.setItemText(9, _translate("SpineFusion", "胸8"))
        self.CB_Fusion3_2.setItemText(10, _translate("SpineFusion", "胸9"))
        self.CB_Fusion3_2.setItemText(11, _translate("SpineFusion", "胸10"))
        self.CB_Fusion3_2.setItemText(12, _translate("SpineFusion", "胸11"))
        self.CB_Fusion3_2.setItemText(13, _translate("SpineFusion", "胸12"))
        self.CB_Fusion3_2.setItemText(14, _translate("SpineFusion", "腰1"))
        self.CB_Fusion3_2.setItemText(15, _translate("SpineFusion", "腰2"))
        self.CB_Fusion3_2.setItemText(16, _translate("SpineFusion", "腰3"))
        self.CB_Fusion3_2.setItemText(17, _translate("SpineFusion", "腰4"))
        self.CB_Fusion3_2.setItemText(18, _translate("SpineFusion", "腰5"))
        self.CB_Fusion3_3.setItemText(0, _translate("SpineFusion", "无"))
        self.CB_Fusion3_3.setItemText(1, _translate("SpineFusion", "颈7"))
        self.CB_Fusion3_3.setItemText(2, _translate("SpineFusion", "胸1"))
        self.CB_Fusion3_3.setItemText(3, _translate("SpineFusion", "胸2"))
        self.CB_Fusion3_3.setItemText(4, _translate("SpineFusion", "胸3"))
        self.CB_Fusion3_3.setItemText(5, _translate("SpineFusion", "胸4"))
        self.CB_Fusion3_3.setItemText(6, _translate("SpineFusion", "胸5"))
        self.CB_Fusion3_3.setItemText(7, _translate("SpineFusion", "胸6"))
        self.CB_Fusion3_3.setItemText(8, _translate("SpineFusion", "胸7"))
        self.CB_Fusion3_3.setItemText(9, _translate("SpineFusion", "胸8"))
        self.CB_Fusion3_3.setItemText(10, _translate("SpineFusion", "胸9"))
        self.CB_Fusion3_3.setItemText(11, _translate("SpineFusion", "胸10"))
        self.CB_Fusion3_3.setItemText(12, _translate("SpineFusion", "胸11"))
        self.CB_Fusion3_3.setItemText(13, _translate("SpineFusion", "胸12"))
        self.CB_Fusion3_3.setItemText(14, _translate("SpineFusion", "腰1"))
        self.CB_Fusion3_3.setItemText(15, _translate("SpineFusion", "腰2"))
        self.CB_Fusion3_3.setItemText(16, _translate("SpineFusion", "腰3"))
        self.CB_Fusion3_3.setItemText(17, _translate("SpineFusion", "腰4"))
        self.CB_Fusion3_3.setItemText(18, _translate("SpineFusion", "腰5"))
        self.groupBox_2.setTitle(_translate("SpineFusion", "第二组锥体融合"))
        self.CB_Fusion2_1.setItemText(0, _translate("SpineFusion", "无"))
        self.CB_Fusion2_1.setItemText(1, _translate("SpineFusion", "颈7"))
        self.CB_Fusion2_1.setItemText(2, _translate("SpineFusion", "胸1"))
        self.CB_Fusion2_1.setItemText(3, _translate("SpineFusion", "胸2"))
        self.CB_Fusion2_1.setItemText(4, _translate("SpineFusion", "胸3"))
        self.CB_Fusion2_1.setItemText(5, _translate("SpineFusion", "胸4"))
        self.CB_Fusion2_1.setItemText(6, _translate("SpineFusion", "胸5"))
        self.CB_Fusion2_1.setItemText(7, _translate("SpineFusion", "胸6"))
        self.CB_Fusion2_1.setItemText(8, _translate("SpineFusion", "胸7"))
        self.CB_Fusion2_1.setItemText(9, _translate("SpineFusion", "胸8"))
        self.CB_Fusion2_1.setItemText(10, _translate("SpineFusion", "胸9"))
        self.CB_Fusion2_1.setItemText(11, _translate("SpineFusion", "胸10"))
        self.CB_Fusion2_1.setItemText(12, _translate("SpineFusion", "胸11"))
        self.CB_Fusion2_1.setItemText(13, _translate("SpineFusion", "胸12"))
        self.CB_Fusion2_1.setItemText(14, _translate("SpineFusion", "腰1"))
        self.CB_Fusion2_1.setItemText(15, _translate("SpineFusion", "腰2"))
        self.CB_Fusion2_1.setItemText(16, _translate("SpineFusion", "腰3"))
        self.CB_Fusion2_1.setItemText(17, _translate("SpineFusion", "腰4"))
        self.CB_Fusion2_1.setItemText(18, _translate("SpineFusion", "腰5"))
        self.CB_Fusion2_2.setItemText(0, _translate("SpineFusion", "无"))
        self.CB_Fusion2_2.setItemText(1, _translate("SpineFusion", "颈7"))
        self.CB_Fusion2_2.setItemText(2, _translate("SpineFusion", "胸1"))
        self.CB_Fusion2_2.setItemText(3, _translate("SpineFusion", "胸2"))
        self.CB_Fusion2_2.setItemText(4, _translate("SpineFusion", "胸3"))
        self.CB_Fusion2_2.setItemText(5, _translate("SpineFusion", "胸4"))
        self.CB_Fusion2_2.setItemText(6, _translate("SpineFusion", "胸5"))
        self.CB_Fusion2_2.setItemText(7, _translate("SpineFusion", "胸6"))
        self.CB_Fusion2_2.setItemText(8, _translate("SpineFusion", "胸7"))
        self.CB_Fusion2_2.setItemText(9, _translate("SpineFusion", "胸8"))
        self.CB_Fusion2_2.setItemText(10, _translate("SpineFusion", "胸9"))
        self.CB_Fusion2_2.setItemText(11, _translate("SpineFusion", "胸10"))
        self.CB_Fusion2_2.setItemText(12, _translate("SpineFusion", "胸11"))
        self.CB_Fusion2_2.setItemText(13, _translate("SpineFusion", "胸12"))
        self.CB_Fusion2_2.setItemText(14, _translate("SpineFusion", "腰1"))
        self.CB_Fusion2_2.setItemText(15, _translate("SpineFusion", "腰2"))
        self.CB_Fusion2_2.setItemText(16, _translate("SpineFusion", "腰3"))
        self.CB_Fusion2_2.setItemText(17, _translate("SpineFusion", "腰4"))
        self.CB_Fusion2_2.setItemText(18, _translate("SpineFusion", "腰5"))
        self.CB_Fusion2_3.setItemText(0, _translate("SpineFusion", "无"))
        self.CB_Fusion2_3.setItemText(1, _translate("SpineFusion", "颈7"))
        self.CB_Fusion2_3.setItemText(2, _translate("SpineFusion", "胸1"))
        self.CB_Fusion2_3.setItemText(3, _translate("SpineFusion", "胸2"))
        self.CB_Fusion2_3.setItemText(4, _translate("SpineFusion", "胸3"))
        self.CB_Fusion2_3.setItemText(5, _translate("SpineFusion", "胸4"))
        self.CB_Fusion2_3.setItemText(6, _translate("SpineFusion", "胸5"))
        self.CB_Fusion2_3.setItemText(7, _translate("SpineFusion", "胸6"))
        self.CB_Fusion2_3.setItemText(8, _translate("SpineFusion", "胸7"))
        self.CB_Fusion2_3.setItemText(9, _translate("SpineFusion", "胸8"))
        self.CB_Fusion2_3.setItemText(10, _translate("SpineFusion", "胸9"))
        self.CB_Fusion2_3.setItemText(11, _translate("SpineFusion", "胸10"))
        self.CB_Fusion2_3.setItemText(12, _translate("SpineFusion", "胸11"))
        self.CB_Fusion2_3.setItemText(13, _translate("SpineFusion", "胸12"))
        self.CB_Fusion2_3.setItemText(14, _translate("SpineFusion", "腰1"))
        self.CB_Fusion2_3.setItemText(15, _translate("SpineFusion", "腰2"))
        self.CB_Fusion2_3.setItemText(16, _translate("SpineFusion", "腰3"))
        self.CB_Fusion2_3.setItemText(17, _translate("SpineFusion", "腰4"))
        self.CB_Fusion2_3.setItemText(18, _translate("SpineFusion", "腰5"))
        self.groupBox.setTitle(_translate("SpineFusion", "第一组锥体融合"))
        self.CB_Fusion1_1.setItemText(0, _translate("SpineFusion", "无"))
        self.CB_Fusion1_1.setItemText(1, _translate("SpineFusion", "颈7"))
        self.CB_Fusion1_1.setItemText(2, _translate("SpineFusion", "胸1"))
        self.CB_Fusion1_1.setItemText(3, _translate("SpineFusion", "胸2"))
        self.CB_Fusion1_1.setItemText(4, _translate("SpineFusion", "胸3"))
        self.CB_Fusion1_1.setItemText(5, _translate("SpineFusion", "胸4"))
        self.CB_Fusion1_1.setItemText(6, _translate("SpineFusion", "胸5"))
        self.CB_Fusion1_1.setItemText(7, _translate("SpineFusion", "胸6"))
        self.CB_Fusion1_1.setItemText(8, _translate("SpineFusion", "胸7"))
        self.CB_Fusion1_1.setItemText(9, _translate("SpineFusion", "胸8"))
        self.CB_Fusion1_1.setItemText(10, _translate("SpineFusion", "胸9"))
        self.CB_Fusion1_1.setItemText(11, _translate("SpineFusion", "胸10"))
        self.CB_Fusion1_1.setItemText(12, _translate("SpineFusion", "胸11"))
        self.CB_Fusion1_1.setItemText(13, _translate("SpineFusion", "胸12"))
        self.CB_Fusion1_1.setItemText(14, _translate("SpineFusion", "腰1"))
        self.CB_Fusion1_1.setItemText(15, _translate("SpineFusion", "腰2"))
        self.CB_Fusion1_1.setItemText(16, _translate("SpineFusion", "腰3"))
        self.CB_Fusion1_1.setItemText(17, _translate("SpineFusion", "腰4"))
        self.CB_Fusion1_1.setItemText(18, _translate("SpineFusion", "腰5"))
        self.CB_Fusion1_2.setItemText(0, _translate("SpineFusion", "无"))
        self.CB_Fusion1_2.setItemText(1, _translate("SpineFusion", "颈7"))
        self.CB_Fusion1_2.setItemText(2, _translate("SpineFusion", "胸1"))
        self.CB_Fusion1_2.setItemText(3, _translate("SpineFusion", "胸2"))
        self.CB_Fusion1_2.setItemText(4, _translate("SpineFusion", "胸3"))
        self.CB_Fusion1_2.setItemText(5, _translate("SpineFusion", "胸4"))
        self.CB_Fusion1_2.setItemText(6, _translate("SpineFusion", "胸5"))
        self.CB_Fusion1_2.setItemText(7, _translate("SpineFusion", "胸6"))
        self.CB_Fusion1_2.setItemText(8, _translate("SpineFusion", "胸7"))
        self.CB_Fusion1_2.setItemText(9, _translate("SpineFusion", "胸8"))
        self.CB_Fusion1_2.setItemText(10, _translate("SpineFusion", "胸9"))
        self.CB_Fusion1_2.setItemText(11, _translate("SpineFusion", "胸10"))
        self.CB_Fusion1_2.setItemText(12, _translate("SpineFusion", "胸11"))
        self.CB_Fusion1_2.setItemText(13, _translate("SpineFusion", "胸12"))
        self.CB_Fusion1_2.setItemText(14, _translate("SpineFusion", "腰1"))
        self.CB_Fusion1_2.setItemText(15, _translate("SpineFusion", "腰2"))
        self.CB_Fusion1_2.setItemText(16, _translate("SpineFusion", "腰3"))
        self.CB_Fusion1_2.setItemText(17, _translate("SpineFusion", "腰4"))
        self.CB_Fusion1_2.setItemText(18, _translate("SpineFusion", "腰5"))
        self.CB_Fusion1_3.setItemText(0, _translate("SpineFusion", "无"))
        self.CB_Fusion1_3.setItemText(1, _translate("SpineFusion", "颈7"))
        self.CB_Fusion1_3.setItemText(2, _translate("SpineFusion", "胸1"))
        self.CB_Fusion1_3.setItemText(3, _translate("SpineFusion", "胸2"))
        self.CB_Fusion1_3.setItemText(4, _translate("SpineFusion", "胸3"))
        self.CB_Fusion1_3.setItemText(5, _translate("SpineFusion", "胸4"))
        self.CB_Fusion1_3.setItemText(6, _translate("SpineFusion", "胸5"))
        self.CB_Fusion1_3.setItemText(7, _translate("SpineFusion", "胸6"))
        self.CB_Fusion1_3.setItemText(8, _translate("SpineFusion", "胸7"))
        self.CB_Fusion1_3.setItemText(9, _translate("SpineFusion", "胸8"))
        self.CB_Fusion1_3.setItemText(10, _translate("SpineFusion", "胸9"))
        self.CB_Fusion1_3.setItemText(11, _translate("SpineFusion", "胸10"))
        self.CB_Fusion1_3.setItemText(12, _translate("SpineFusion", "胸11"))
        self.CB_Fusion1_3.setItemText(13, _translate("SpineFusion", "胸12"))
        self.CB_Fusion1_3.setItemText(14, _translate("SpineFusion", "腰1"))
        self.CB_Fusion1_3.setItemText(15, _translate("SpineFusion", "腰2"))
        self.CB_Fusion1_3.setItemText(16, _translate("SpineFusion", "腰3"))
        self.CB_Fusion1_3.setItemText(17, _translate("SpineFusion", "腰4"))
        self.CB_Fusion1_3.setItemText(18, _translate("SpineFusion", "腰5"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SpineFusion = QtWidgets.QWidget()
    ui = Ui_SpineFusion()
    ui.setupUi(SpineFusion)
    SpineFusion.show()
    sys.exit(app.exec_())

